---
baseURL: "/"
defaultContentLanguage: en
languageCode: en-us
languages:
  en:
    languageName: English
    weight: '1'
  es:
    languageName: Spanish
    weight: '2'
    logo: images/weather_es_w.png
    title: Tiempo y Clima presentados por Weather Gizmo
    address_title: Donde
    follow: Redes
    categories: Categorias
    category: Categoria
    read_more: Leer mas...
    post_available_in: Este texto esta desponible en
  ru:
    languageName: Russian
    weight: '3'
    logo: images/weather_ru_w.png
    address: Минск / Киев / Несвиж
    title: 'Погода и Климат: сайт от Weather Gizmo'
    read_more: Дальше...
    address_title: Где
    contact_info: Контакты
    follow: Социальные сети
    previous: "« Вперёд"
    next: "Назад »"
    post_by: Опубликовано
    latest_post: Последние материалы
    tag: Тег
    tags: Теги
    categories: Категории
    category: Категория
    post_available_in: Пост также доступен на следующих языках
    menu:
      main:
      - URL: /ru/about/
        name: "О&nbsp;Сайте"
        weight: 1
  uk:
    languageName: Ukranian
    logo: images/weather_ru_w.png
    weight: '4'
    follow: Мережи
    address: Мінськ / Київ / Несвіж
    title: 'Погода і Клімат: сайт від Weather Gizmo'
    read_more: Далi...
    address_title: Де
    contact_info: Контакти
    previous: "« Вперед"
    next: "Назад »"
    post_by: Опубліковано
    latest_post: Останні матеріали
    tags: Теги
    tag: Тег
    categories: Категорії
    category: Категорія
    post_available_in: Пост також доступний наступними мовами
  be:
    languageName: Belarusian
    logo: images/weather_by.png
    weight: '5'
    address: Мiнск / Нясвиж
    title: 'Пагода ды Клiмат: сайт ад Weather Gizmo'
    read_more: Далей...
    address_title: Дзе
    contact_info: Кантакты
    follow: Сацыяльныя сеткi
    previous: "« Наперад"
    next: "У мiнулае »"
    post_by: Апублiкавана
    latest_post: Апошнiя матерыялы
    tags: Тегi
    tag: Тег
    categories: Категорыi
    category: Категорыя
    post_available_in: Гэты пост таксама ёсць на наступных мовах
title: 'Weather and Climate: a site by Weather Gizmo'
module:
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: static
      target: assets/images
    - source: exampleSite/static/images
      target: static/images
summaryLength: '39'
paginate: '12'
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    - link: plugins/smartbanner/smartbanner.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
    - link: plugins/smartbanner/smartbanner.js
  baseURL: https://weather-aware.com
  logo: images/weather_a.png
  home: Home
  layout: '1'
  description: Weather trivia for the changing world
  preloader: false
  search: false
  author: Weather Gizmo
  author_image: images/weather_logo.png
  bio: Weather trivia for the changing world
  email: weather@adekvat.us
  address: Minsk / Kyiv / Nesvizh
  contact_form_action: "#"
  google_analitycs_id: G-5QEGHYVE5K
  copyright: "&copy; 2021"
  read_more: Read more
  address_title: Adress
  contact_info: Contact Info
  follow: Follow
  previous: "« Previous"
  next: Next »
  post_by: Post by
  latest_post: LATEST POST
  tag: TAG
  tags: TAG
  categories: CATEGORIES
  category: CATEGORY
  post_available_in: This post is also available in
  instafeed:
    enable: false
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-facebook
    link: https://www.facebook.com/weathergizmo/
  - icon: ti-twitter-alt
    link: https://twitter.com/gizmoweather
menu:
  main:
  - URL: about
    name: About
    weight: 1
