---
baseURL: "/"
defaultContentLanguage: en
languageCode: en-us
languages:
  en:
    languageName: English
    weight: "1"
  es:
    languageName: Spanish
    weight: "2"
  ru:
    languageName: Russian
    weight: "3"
    description: Что-то про погоду
    address: Минск / Нясвиж
  uk:
    languageName: United Kingdom
    weight: "4"
title: 'Weather and Climate: a site by Weather Gizmo'
module:
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
summaryLength: "10"
paginate: "6"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    - link: plugins/smartbanner/smartbanner.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
    - link: plugins/smartbanner/smartbanner.js
  baseURL: https://weather-aware.com
  logo: images/weather_a.png
  home: Home
  layout: "1"
  description: Weather trivia for the changing world
  preloader: false
  search: false
  author: Weather Gizmo
  author_image: images/weather_logo.png
  bio: Weather trivia for the changing world
  mobile: "+90 546 645 74 67"
  email: we@weather-aware.com
  address: Minsk / Kyiv / Nesvizh
  contact_form_action: "#"
  google_analitycs_id: G-5QEGHYVE5K
  copyright: Copyright &copy; 2021 a theme by [themefisher.com](themefisher.com)
  instafeed:
    enable: false
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social:
  - icon: ti-facebook
    URL: https://www.facebook.com/weathergizmo/
  - icon: ti-twitter-alt
    URL: https://twitter.com/gizmoweather
menu:
  main:
  - name: About
    URL: about
    weight: "2"
