[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.74.3"

[[redirects]]
  from = "https://weather-gizmo.com/*"
  to = "https://weather-aware.com/:splat"
  status = 301
  force = true
